### ISSUE TITLE
Include all header values

### ISSUE THREAD

**Issue by kokoabim** [amingolmahalle/HttpClientToCurlGenerator#17]
When appending header values, use `string.Join("; ", header.Value)` instead to include all header values.

**Comment by amingolmahalle** [comment]
Please write more details about your issue. or write an example so that I understand what you mean.
Thank you

**Comment by kokoabim** [comment]
Instead of using `header.Value?.FirstOrDefault()` on the following lines, use `string.Join("; ", header.Value)`. Header values can have more than one value, e.q. `Cookie`, hence the type of [HttpHeaders](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.headers.httpheaders?view=net-8.0):
- https://github.com/amingolmahalle/HttpClientToCurlGenerator/blob/3fd81a431bae87548fd86d91d49ecbe58d99c817/src/HttpClientToCurl/Builder.cs#L106C22-L106C22
- https://github.com/amingolmahalle/HttpClientToCurlGenerator/blob/3fd81a431bae87548fd86d91d49ecbe58d99c817/src/HttpClientToCurl/Builder.cs#L121C61-L121C67
- https://github.com/amingolmahalle/HttpClientToCurlGenerator/blob/3fd81a431bae87548fd86d91d49ecbe58d99c817/src/HttpClientToCurl/Builder.cs#L136C61-L136C67

**Comment by Sabermotamedi** [comment]
Hello @amingolmahalle,

Thank you for your comment. I've received feedback from @kokoabim regarding the handling of header values in the code. The suggestion is to use string.Join("; ", header.Value) instead of header.Value?.FirstOrDefault() to accommodate cases where headers may have multiple values.

I'll make the necessary adjustments to the code to address this issue. Once the changes are complete, I'll create a pull request for your review.

If you have any specific preferences or additional considerations, please let me know.

Appreciate your attention to this matter.

**Comment by amingolmahalle** [comment]
Hello @Sabermotamedi.
This issue is assigned to you.
Thanks.
